name: Build and Deploy

on:
  push:
    branches:
      - main
      - dev
      - class-notes

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install and Build
        run: |
          npm ci
          npm run build-site

      - name: Push build to deployment branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: ${{ github.ref_name }}-build
          commit_message: 'build: ${{ github.sha }}'
